name = "public-bucket"
main = "./dist/worker.mjs"
compatibility_date = "2024-05-15"
r2_buckets = [{ binding = "BUCKET", bucket_name = "carpark-dev-0" }]

[build]
command = "npm run build"

[vars]
DEBUG = "true"

# PROD!
[env.carpark-production]
account_id = "fffa4b4363a7e5250af8357087263b3a"
r2_buckets = [{ binding = "BUCKET", bucket_name = "carpark-prod-0" }]

[env.carpark-production.vars]
DEBUG = "false"

# STAGING!
[env.carpark-staging]
account_id = "fffa4b4363a7e5250af8357087263b3a"
r2_buckets = [{ binding = "BUCKET", bucket_name = "carpark-staging-0" }]
